# row column number based on location

In [1]:
import numpy as np

In [2]:
# top right corner location
# top_lat=37.0
# top_lon=68.25
# resolution=0.25

# lat=[74.75,77.00]
# lon=[21.50,23.75]
# top_row=int((top_lat-lat[1])/resolution)
# botm_row=int((top_lat-lat[0])/resolution)
# left_col=int((lon[0]-top_lon)/resolution)
# right_col=int((lon[1]-top_lon)/resolution)

In [3]:
# top right corner location
top_lat=37.0
top_lon=68.25
resolution=0.25
# bufffer of 1.25 degree or 5 pixels
# Rectangle lat lon
# Indore
location=[84.24,24.71]
# # Aurangabad4
# location=[75.35,19.90]
# # Harihar
# location=[75.78,14.58]


topleftPoint=[location[0]-resolution*5,location[1]+resolution*5]
col=int((topleftPoint[0]-top_lon)/0.25)
row=int((top_lat-topleftPoint[1])/0.25)
print('row',[row,row+10])
print('column',[col,col+10])

row [44, 54]
column [58, 68]


In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[6, 7, 8, 9, 10],[6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


array([[2],
       [5]])